# GitHub Pages configuration for MCP RAG documentation
title: MCP RAG Documentation
description: Documentação completa do MCP RAG - Sistema de RAG com MCP para agentes inteligentes
baseurl: "/mcp-rag"
url: "https://seu-usuario.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
navigation:
  - title: Início
    url: /
  - title: Instalação
    url: #instalacao
  - title: Configuração
    url: #configuracao
  - title: Ferramentas
    url: #ferramentas
  - title: Exemplos
    url: #exemplos

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor